import { describe, expect, it } from "vitest";
import dc from "../../public/data/datacenter.json";
import { HUB_POSITIONS, US_BORDERS, US_NATION } from "./usOutline";

describe("usOutline (generated by site/scripts/gen-us-outline.mjs)", () => {
  it("places every published /power hub inside the map frame", () => {
    // a new hub fails here until the generator is rerun with its location
    for (const h of dc.power!.hubs) {
      const p = HUB_POSITIONS[h.code];
      expect(p, `${h.code}: add it to HUBS in site/scripts/gen-us-outline.mjs and rerun`).toBeDefined();
      expect(p.x).toBeGreaterThan(0); expect(p.x).toBeLessThan(975);
      expect(p.y).toBeGreaterThan(0); expect(p.y).toBeLessThan(610);
    }
  });
  it("ships whole-pixel paths small enough to inline", () => {
    expect(US_NATION.startsWith("M")).toBe(true);
    expect(US_NATION.length + US_BORDERS.length).toBeLessThan(60_000);
    expect(US_NATION).not.toMatch(/\d\.\d/);
  });
});
